apiVersion: v1
kind: Service
metadata:
  name: locust
  namespace: puresecure
  labels:
    app: locust
spec:
  type: ClusterIP
  selector:
    app: locust
  ports:
    - name: http
      port: 8089
      targetPort: 8089
      protocol: TCP
