{{- if .Values.redis.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "puresecure.redis.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.redis.replicas }}
  selector:
    matchLabels:
      {{- include "puresecure.redis.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "puresecure.redis.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: redis
          image: {{ .Values.redis.image }}
          ports:
            - containerPort: {{ .Values.redis.port }}
          command:
            - redis-server
            - "--appendonly"
            - "yes"
            - "--maxmemory"
            - {{ .Values.redis.maxmemory | quote }}
            - "--maxmemory-policy"
            - {{ .Values.redis.maxmemoryPolicy | quote }}
          resources:
            {{- toYaml .Values.redis.resources | nindent 12 }}
          readinessProbe:
            exec:
              command: ["redis-cli", "ping"]
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            exec:
              command: ["redis-cli", "ping"]
            initialDelaySeconds: 10
            periodSeconds: 30
{{- end }}
