{{- if .Values.grafana.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-auth-config
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "puresecure.grafana.labels" . | nindent 4 }}
data:
  # -- Server
  GF_SERVER_ROOT_URL: {{ .Values.grafana.auth.serverRootUrl | quote }}
  GF_SERVER_DOMAIN: {{ .Values.grafana.auth.serverDomain | quote }}
  # -- Users
  GF_USERS_ALLOW_SIGN_UP: {{ .Values.grafana.auth.usersAllowSignUp | quote }}
  # -- Login form
  GF_AUTH_DISABLE_LOGIN_FORM: {{ .Values.grafana.auth.disableLoginForm | quote }}
  # -- Disable Azure AD OAuth
  GF_AUTH_AZUREAD_ENABLED: "false"
  # -- Home dashboard
  GF_DEFAULT_HOME_DASHBOARD_PATH: ""
{{- end }}
