apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "puresecure.app.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.app.config }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
