apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cwe-data-pvc
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "puresecure.app.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.app.storage.storageClass }}
  resources:
    requests:
      storage: {{ .Values.app.storage.size }}
