apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: puresecure
  labels:
    app: cwe-explorer
data:
  PYTHONUNBUFFERED: "1"
  # Set these to your Azure Entra ID app registration values
  AZURE_TENANT_ID: "d1d16433-e375-4076-a7ea-c57bb79df0de"
  AZURE_CLIENT_ID: "7587a506-259a-4198-bcc5-5a6d629453f0"
  CORS_ORIGINS: "https://reondev.top,http://localhost:8000,http://127.0.0.1:8000"
  GRAFANA_URL: "https://grafana.reondev.top"
  PROMETHEUS_URL: ""
  LOCUST_URL: ""
