apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: puresecure
  labels:
    app: cwe-explorer
data:
  PYTHONUNBUFFERED: "1"
  # Set these to your Azure Entra ID app registration values
  AZURE_TENANT_ID: ""
  AZURE_CLIENT_ID: ""
  CORS_ORIGINS: "http://localhost:8000,http://127.0.0.1:8000"
  GRAFANA_URL: "http://localhost:3000"
  PROMETHEUS_URL: "http://localhost:9090"
  LOCUST_URL: "http://localhost:8089"
