apiVersion: v1
kind: Service
metadata:
  name: web
  namespace: puresecure
  labels:
    app: cwe-explorer
spec:
  type: ClusterIP
  selector:
    app: cwe-explorer
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      protocol: TCP
