apiVersion: v1
kind: Service
metadata:
  name: kiali
  namespace: {{ .Values.namespace }}
  labels:
    app: kiali
    app.kubernetes.io/name: kiali
spec:
  type: ClusterIP
  selector:
    app: kiali
  ports:
    - { name: http, port: {{ .Values.kiali.port }}, targetPort: api-http, protocol: TCP }
