apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-data-pvc
  namespace: puresecure
  labels:
    app: grafana
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  # Docker Desktop: uses default "hostpath" StorageClass
  # AKS: change to storageClassName: managed-csi
