# Values for Bitnami ExternalDNS Helm Chart
# Usage: helm upgrade --install external-dns bitnami/external-dns -n external-dns --create-namespace -f helm/external-dns-values.yaml
provider: azure

env:
  - name: AZURE_CLIENT_ID
    value: "d5880997-4a9a-4323-bd64-c71a27450058"

secretConfiguration:
  enabled: true
  mountPath: "/etc/kubernetes"
  data:
    azure.json: |
      {
        "tenantId": "d1d16433-e375-4076-a7ea-c57bb79df0de",
        "subscriptionId": "dfed6615-05cd-434d-b0e0-7dea9e050738",
        "resourceGroup": "sa",
        "useWorkloadIdentityExtension": true
      }

serviceAccount:
  create: true
  name: external-dns-sa
  annotations:
    # This instructs Kubernetes to use Azure Workload Identity to fetch Azure tokens automatically
    azure.workload.identity/client-id: "d5880997-4a9a-4323-bd64-c71a27450058"

podLabels:
  azure.workload.identity/use: "true"

# Tell ExternalDNS to watch Traefik IngressRoutes and standard Services to grab IP addresses
sources:
  - service
  - ingress
  - traefik-proxy

# Restrict what domains it is allowed to modify in Azure DNS!
domainFilters:
  - reondev.top

# A unique identifier so ExternalDNS knows which records it created vs humans created
txtOwnerId: "puresecure-aks"

rbac:
  create: true
